# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 91f1420
_src_path: https://github.com/Matgenix/datalab-item-plugin-template
author_email: julien.bouquiaux@matgenix.com
author_fullname: Julien Bouquiaux
copyright_date: '2026'
copyright_holder: ''
copyright_holder_email: ''
include_custom_panel: true
item_class_name: MixedSolution
item_type_name: example-mixed-solutions
package_name: datalab_item_plugin_example_custom_vue
project_name: datalab-item-plugin-example-custom-vue
repository_name: datalab-item-plugin-example-custom-vue
repository_namespace: Matgenix
short_description: ''
